In [1]:
import pandas as pd 
import numpy as np
from typing import Union
from scipy.sparse import csr_matrix, csc_matrix

# class TermStrengthFeatureExtractor:
#     """
#     Calculates term strength according to http://mlwiki.org/index.php/Term_Strength
#     """
#     def __init__(self):
#         self.term_strength = {}
    
#     def fit(self, X, y):
#         """
#         Fit feature extractor
#         Arguments:
#             X -  presense of word (binary output from CountVectorizer)
#             y - array-like with class labels for X
#         """
#         if isinstance(y, np.ndarray):
#             classes = np.unique() 
#         elif isinstance(y, (pd.Series, pd.DataFrame)):
#             classes = y.unique()
        
#         for cls in classes:
#             idx = np.where(y == cls)[0] # might need [0] to unbox the tuple
#             X[idx]
            


In [20]:
from scipy.special import comb

In [38]:
test_arr = np.array([[0,1,0,0,0,1,0], [1,1,1,0,0,0,0], [1,1,0,0,0,1,1],  [1,1,0,1,0,1,0],  [1,1,0,1,0,1,1]])

In [39]:
test_arr

array([[0, 1, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 1, 1]])

In [40]:
comb(1,2)

0.0

w1 = 6/10
w2 = 10/10
w3 = 0
w4 = 3/9
w5 = 0
w6 = 6/10
w7 = 1/7

In [41]:
csr = csr_matrix(test_arr)

In [114]:
# test_csr = csr[[0,1]]
test_csc = csc_matrix(csr)

In [81]:
test_csc[:,0].toarray()

array([[0.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [42]:
n_t = csr.sum(axis=0)

In [43]:
n_t

matrix([[4, 5, 1, 2, 0, 4, 2]])

In [45]:
s_t = np.nan_to_num(comb(n_t, 2) / (comb(csr.shape[0], 2) - comb(csr.shape[0]-n_t, 2)))

/var/folders/x2/lgb5qv_x50577yqt3p7rmydm0000gn/T/ipykernel_2469/3388928679.py:1: RuntimeWarning: invalid value encountered in true_divide
  s_t = np.nan_to_num(comb(n_t, 2) / (comb(csr.shape[0], 2) - comb(csr.shape[0]-n_t, 2)))


In [82]:
def csr_row_set_nz_to_val(csr, row, value=0):
    """Set all nonzero elements (elements currently in the sparsity pattern)
    to the given value. Useful to set to 0 mostly.
    """
    if not isinstance(csr, csr_matrix):
        raise ValueError('Matrix given must be of CSR format.')
    csr.data[csr.indptr[row]:csr.indptr[row+1]] = value
    return csr

def csc_col_set_nz_to_val(csc, col, value=1):
    if not isinstance(csc, csc_matrix):
        raise ValueError('Matrix given must be of CSC format')
    csc.data[csc.indptr[col]:csc.indptr[col+1]] = value
    return csc 

In [115]:
test_csc.toarray()

array([[0, 1, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 1, 1]])

In [116]:
test = csc_col_set_nz_to_val(test_csc, 0, 0.5)

In [118]:
test.toarray()

array([[0, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 1]])

In [121]:
test = test.asfptype()

In [122]:
test.toarray()

array([[0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 1.]])